name: kidney
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_animate: ^2.0.1
  readmore: ^2.1.0
  url_launcher: ^6.1.7
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  provider: ^6.0.4
  quickalert: ^1.0.1
  shared_preferences: ^2.0.15
  cloud_firestore: ^4.1.0
  video_player: ^2.4.8
  youtube_player_flutter: ^8.1.1
  flutter_local_notifications: ^12.0.4
  flutter_native_timezone: ^2.0.0
  icon_broken: ^1.1.0
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
