// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdmORgfbJIWkDbvw2rxPfxBXDFBLbSbCk',
    appId: '1:495502066368:web:f535dd2e937b8da8ff6325',
    messagingSenderId: '495502066368',
    projectId: 'kidney-a0523',
    authDomain: 'kidney-a0523.firebaseapp.com',
    storageBucket: 'kidney-a0523.appspot.com',
    measurementId: 'G-7JN0RV0F35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMRtfJfRqRJVuYJb2qTxXmaQat109lqXQ',
    appId: '1:495502066368:android:4c53a9fac014ff8cff6325',
    messagingSenderId: '495502066368',
    projectId: 'kidney-a0523',
    storageBucket: 'kidney-a0523.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLxoZg-9OBEWAnEAdXPIpu_wouo7nSIak',
    appId: '1:495502066368:ios:2fed5f405fca1118ff6325',
    messagingSenderId: '495502066368',
    projectId: 'kidney-a0523',
    storageBucket: 'kidney-a0523.appspot.com',
    iosClientId: '495502066368-j59p175bh3egq2n8936f33b46fmqv1aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.kidney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLxoZg-9OBEWAnEAdXPIpu_wouo7nSIak',
    appId: '1:495502066368:ios:2fed5f405fca1118ff6325',
    messagingSenderId: '495502066368',
    projectId: 'kidney-a0523',
    storageBucket: 'kidney-a0523.appspot.com',
    iosClientId: '495502066368-j59p175bh3egq2n8936f33b46fmqv1aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.kidney',
  );
}
